# Generated by Django 2.2.7 on 2019-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_auto_20191117_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='money',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
