# Generated by Django 2.2.7 on 2019-11-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_auto_20191118_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='moneyValue',
        ),
    ]
